### ISSUE TITLE
Questions about the package graceful

### ISSUE THREAD

**Issue by RussellLuo** [Scalingo/go-utils#65]
After reading the implementation of the package `graceful`, I have some questions:
1. Why is there some [security code](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service.go#L118-L127)?
    - Per the docs of [Server.Serve](https://golang.org/pkg/net/http/#Server.Serve),  Serve always returns a non-nil error, so by what means can the code be reached?
    - Or in other words, as the comment have said "Normally", in what **abnormal scenario** will Serve return a nil error?
2. As far as I can see, the channel `s.stopped` can only receive event ([here](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service_signals.go#L31) and [here](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service_signals.go#L45)) or be closed ([here](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service_signals.go#L33) and [here](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service_signals.go#L47)) by signals. So I think the final [receiving operation](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service.go#L128) will be blocked if the security code is reached?
3. In case of [the failure of the child process](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service_signals.go#L38) (due to the bug of new binary or the error in new configuration), the parent process [is shutdown](https://github.com/Scalingo/go-utils/blob/213afb2b25a1d8b07d2ac2e97238ed07817658bd/graceful/service_signals.go#L43), why don't we keep it running for serving requests?

Thanks in advance! BTW, I come here from [the awesome article](https://scalingo.com/articles/2014/12/19/graceful-server-restart-with-go.html) :)

**Comment by Soulou** [comment]
Hi @RussellLuo thanks for these questions. You might have noticed that the article has a few years now and new methods have been integrated into the go standard library, especially `http.Server#Shutdown`

Concerning your questions:

1. You're write that this code is quite clumsy/unjustified. The reality is that I didn't the mention in the godoc about the fact that Server returns always a non-nil error. So that's right it should be remove probably.

2. This point was valid if the security code is rechable, as the godoc is saying, it shouldn't be reachable at all. So let's say it's one less problem here.

3. You're right, in the case the new binary is not able to start, the parent will also die and requests would be dropped, so keeping the parent process is probably the best behavior here.

Thanks for those remarks and for taking interest in this package. I'll close this issue as soon your remarks have been taken into account in the code.

**Comment by RussellLuo** [comment]
@Soulou Thanks for your quick reply!

As for the 3rd question, after careful thought, I think keeping the parent process is still not enough, since [os.StartProcess](https://golang.org/pkg/os/#StartProcess) can only detect and return PathError (see [doc](https://golang.org/pkg/os/#StartProcess) and [code](https://github.com/golang/go/blob/master/src/os/exec_posix.go#L22)).

In other words, if the child process is successfully started (with correct binary path), but fails in subsequent processing (like encounter error when parsing configuration), the parent can not be notified then parent process will still be shutdown.

A new library named [tableflip](https://blog.cloudflare.com/graceful-upgrades-in-go/) used Pipe to solve the above issue (i.e. [notifying the parent](https://github.com/cloudflare/tableflip/blob/3728e38f7e51da2c570af557aabefd1798b1c4bb/parent.go#L73)).

**Comment by Soulou** [comment]
Cloudflare library looks great, we'll definitely have a look at this, thanks for mentioning. It would be definitely better if the new process can certify that it can receive connections before giving up the parent.

**Comment by RussellLuo** [comment]
My pleasure:) Going to close this issue, and thanks for your kindly reply again.
